# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf4110a4a9ce0e769877730807dd86e3c861add44ead5808d225a532371c7c81012364cfc936143c38a3a186442ecd4b7fe91f2685c55291132cabe4d684150d

test:
  secret_key_base: 3a7fda7097c7781dbd2bc4f884c9103c74f29a54f913100e4ada2b0034705a12faef868dae06a19ad375b46f563e0c322ff5ddba250486caeab217595902c037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
